version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build the application
          command: npm run build-pre
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: dist
          to: 's3://riftlink-webapp-pre'
          arguments: |
            --cache-control "max-age=86400" \
            --delete \
            --exclude *.html
      - aws-s3/sync:
          from: dist
          to: 's3://riftlink-webapp-pre'
          arguments: |
            --cache-control "no-cache" \
            --include *.html \
            --exclude *